## Basic Configuration

baseurl = "https://svenmilewski.github.io/svenmilewski.de"
builddrafts = false
canonifyurls = true
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Sven Milewski"
title = "Sven Milewski"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
# googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Sven Milewski"
intro = "Software & Cloud Engineer"
description = "currently [@fulfillmenttools](https://fulfillmenttools.com)"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "svenmilewski"
linkedin = "svenmilewski"
email = "mail@svenmilewski.de"
# pgp = "<key_fingerprint>"

## Extras
[params.extra]
copyright = "© 2023. Sven Milewski. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false

## Main Menu